# Generated by Django 6.0.1 on 2026-08-25 22:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_trainer_avatar_file_alter_trainer_avatar'),
        ('members', '0002_member_avatar_file_alter_member_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('day_name', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, verbose_name='Día')),
                ('subtitle', models.CharField(default='Empuje (Pecho/Tríceps)', max_length=150, verbose_name='Enfoque / Grupo Muscular')),
                ('is_rest_day', models.BooleanField(default=False, verbose_name='¿Día de Descanso?')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Día de Rutina',
                'verbose_name_plural': 'Días de Rutina',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BodyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Medición')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso Corporal (kg)')),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% Grasa Corporal')),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masa Muscular Estimada (kg)')),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cintura (cm)')),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pecho (cm)')),
                ('photo_front', models.ImageField(blank=True, null=True, upload_to='metrics/photos/', verbose_name='Foto de Progreso')),
                ('photo_url', models.URLField(blank=True, verbose_name='URL Foto Progreso')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to='members.member', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Medición Corporal',
                'verbose_name_plural': 'Mediciones Corporales',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('exercise_name', models.CharField(max_length=150, verbose_name='Ejercicio')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso Logrado (kg)')),
                ('achieved_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Logrado')),
                ('badge_type', models.CharField(choices=[('fire', 'Fuego 🔥'), ('crown', 'Corona 👑'), ('bolt', 'Rayo ⚡'), ('star', 'Estrella ⭐')], default='fire', max_length=20, verbose_name='Insignia / Icono')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='members.member', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Récord Personal (PR)',
                'verbose_name_plural': 'Récords Personales (PRs)',
                'ordering': ['order', '-weight_kg'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Ejercicio')),
                ('muscle_group', models.CharField(default='Pecho', max_length=100, verbose_name='Grupo Muscular')),
                ('series_reps', models.CharField(default='4 x 10', max_length=50, verbose_name='Series x Repeticiones')),
                ('rest_seconds', models.PositiveIntegerField(default=90, verbose_name='Tiempo de Descanso (Segundos)')),
                ('image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&auto=format&fit=crop&q=80', verbose_name='URL de Imagen/Demostración')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas técnicas')),
                ('routine_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='portal.routineday', verbose_name='Día de Rutina')),
            ],
            options={
                'verbose_name': 'Ejercicio de Rutina',
                'verbose_name_plural': 'Ejercicios de Rutina',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(default='Hipertrofia Clásica', max_length=150, verbose_name='Nombre de la Rutina')),
                ('goal', models.CharField(default='Hipertrofia de Empuje: Pecho y Tríceps', max_length=200, verbose_name='Objetivo / Especialidad')),
                ('total_weeks', models.PositiveIntegerField(default=8, verbose_name='Semanas Totales')),
                ('current_week', models.PositiveIntegerField(default=3, verbose_name='Semana Actual')),
                ('progress_percent', models.PositiveIntegerField(default=38, verbose_name='Progreso General (%)')),
                ('trainer_notes', models.TextField(blank=True, default='Para este entrenamiento de empuje, enfócate en la fase excéntrica (bajada) en el Press de Banca. Mantén una bajada controlada de 3 segundos para maximizar el reclutamiento de fibras musculares. Si completas todas las series con buena técnica, incrementa 2.5 kg en la última de press inclinado.', verbose_name='Notas y Consejos del Entrenador')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Rutina Activa?')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='members.member', verbose_name='Socio')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routines', to='classes.trainer', verbose_name='Entrenador Asignado')),
            ],
            options={
                'verbose_name': 'Rutina de Entrenamiento',
                'verbose_name_plural': 'Rutinas de Entrenamiento',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='routineday',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='portal.workoutroutine', verbose_name='Rutina'),
        ),
        migrations.CreateModel(
            name='MemberActivityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('day_name', models.CharField(max_length=20, verbose_name='Día de la Semana')),
                ('day_number', models.PositiveIntegerField(verbose_name='Número de Día')),
                ('status', models.CharField(choices=[('ENTRENADO', 'Entrenado'), ('DESCANSO', 'Descanso'), ('PENDIENTE', 'Pendiente')], default='ENTRENADO', max_length=20, verbose_name='Estado')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_days', to='members.member', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Actividad Diaria',
                'verbose_name_plural': 'Actividades Diarias',
                'ordering': ['date'],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
