# Generated by Django 5.2.17 on 2026-08-25 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_member_avatar_file_alter_member_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Abonado ($)')),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria / QR'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('MERCADOPAGO', 'Mercado Pago')], default='EFECTIVO', max_length=25, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente'), ('ANULADO', 'Anulado / Reembolsado')], default='COMPLETADO', max_length=20, verbose_name='Estado del Pago')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='N° de Comprobante / Recibo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas / Referencia de Transacción')),
                ('auto_renew_membership', models.BooleanField(default=True, verbose_name='¿Extender / Activar Membresía Automáticamente?')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member', verbose_name='Socio / Cliente')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.plan', verbose_name='Plan / Membresía')),
            ],
            options={
                'verbose_name': 'Pago / Cobranza',
                'verbose_name_plural': 'Pagos y Cobranzas',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
