# Generated by Django 5.2.17 on 2026-08-24 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Disciplina')),
                ('color', models.CharField(default='#f5b82e', max_length=20, verbose_name='Color de Identificación (HEX)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='dumbbell', max_length=50, verbose_name='Identificador de Icono')),
            ],
            options={
                'verbose_name': 'Disciplina / Categoría',
                'verbose_name_plural': 'Disciplinas / Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('specialty', models.CharField(max_length=150, verbose_name='Especialidad / Disciplinas')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('avatar', models.URLField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80', verbose_name='Foto / Avatar (URL)')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía / Certificaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('title', models.CharField(max_length=120, verbose_name='Título de la Clase')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día de la Semana')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Fin')),
                ('room', models.CharField(default='Sala Principal', max_length=100, verbose_name='Salón / Box')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='Cupo Máximo')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Horario Activo?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.classcategory', verbose_name='Disciplina')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.trainer', verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Horario Recurrente de Clase',
                'verbose_name_plural': 'Horarios Recurrentes de Clases',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('title', models.CharField(max_length=120, verbose_name='Nombre de la Clase')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Fin')),
                ('room', models.CharField(default='Sala Principal', max_length=100, verbose_name='Salón / Box')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='Cupo Total')),
                ('booked_count', models.PositiveIntegerField(default=0, verbose_name='Cupos Reservados')),
                ('status', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=15, verbose_name='Estado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='classes.classcategory', verbose_name='Disciplina')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='classes.classschedule')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='classes.trainer', verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Sesión de Clase',
                'verbose_name_plural': 'Sesiones de Clases',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
