# Generated by Django 5.2.17 on 2026-08-25 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('status', models.CharField(choices=[('RESERVADO', 'Reservado'), ('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20, verbose_name='Estado de Asistencia')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inscripción')),
                ('notes', models.TextField(blank=True, verbose_name='Notas / Observaciones')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to='members.member', verbose_name='Socio / Miembro')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.classsession', verbose_name='Sesión de Clase')),
            ],
            options={
                'verbose_name': 'Inscripción a Clase',
                'verbose_name_plural': 'Inscripciones a Clases',
                'ordering': ['-booking_date'],
                'constraints': [models.UniqueConstraint(fields=('session', 'member'), name='unique_session_member_booking')],
            },
        ),
    ]
