# Generated by Django 5.2.17 on 2026-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('gym_name', models.CharField(default='Vitalis Fitness Club', max_length=150, verbose_name='Nombre del Gimnasio')),
                ('branch_name', models.CharField(default='Sede Central • Palermo Soho', max_length=150, verbose_name='Nombre de la Sede')),
                ('tax_id', models.CharField(default='30-71829304-5', max_length=50, verbose_name='CUIT / Identificación Fiscal')),
                ('address', models.CharField(default='Av. del Libertador 4500, Palermo, CABA', max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(default='+54 11 4899-2030', max_length=50, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(default='+54 9 11 5500-8822', max_length=50, verbose_name='WhatsApp de Recepción')),
                ('email', models.EmailField(default='contacto@vitalisfitness.com', max_length=254, verbose_name='Email Oficial')),
                ('bank_cbu', models.CharField(default='0000003100045678912345', max_length=100, verbose_name='CBU / CVU Bancario')),
                ('bank_alias', models.CharField(default='VITALIS.FITNESS.PAGO', max_length=100, verbose_name='Alias Bancario / Mercado Pago')),
                ('receipt_footer', models.TextField(default='Gracias por elegir Vitalis Fitness Club. Las cuotas abonadas son personales y no reembolsables.', verbose_name='Mensaje de Pie de Recibo')),
                ('days_advance_notice', models.PositiveIntegerField(default=7, verbose_name='Días de Anticipación para Alerta de Vencimiento')),
                ('grace_period_days', models.PositiveIntegerField(default=3, verbose_name='Días de Gracia para Acceso tras Vencimiento')),
                ('default_class_capacity', models.PositiveIntegerField(default=15, verbose_name='Capacidad por Defecto en Clases')),
            ],
            options={
                'verbose_name': 'Configuración del Gimnasio',
                'verbose_name_plural': 'Configuraciones del Gimnasio',
            },
        ),
    ]
