# Generated by Django 5.2.17 on 2026-08-24 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Duración (días)')),
                ('color', models.CharField(default='#f5b82e', max_length=20, verbose_name='Color Distintivo (HEX)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Beneficios')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo para venta?')),
            ],
            options={
                'verbose_name': 'Plan de Membresía',
                'verbose_name_plural': 'Planes de Membresía',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI / Cédula')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Prefiero no decir')], default='M', max_length=1, verbose_name='Género')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('avatar', models.URLField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80', verbose_name='Foto / Avatar (URL)')),
                ('status', models.CharField(choices=[('ACTIVA', 'Activa'), ('PENDIENTE', 'Pendiente'), ('VENCIDO', 'Vencido'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=15, verbose_name='Estado de Membresía')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contacto de Emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de Emergencia')),
                ('medical_notes', models.TextField(blank=True, verbose_name='Observaciones Médicas / Físicas')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.plan', verbose_name='Plan Contratado')),
            ],
            options={
                'verbose_name': 'Socio / Miembro',
                'verbose_name_plural': 'Socios / Miembros',
                'ordering': ['-created_at'],
            },
        ),
    ]
