# Generated by Django 5.2.17 on 2026-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/members/', verbose_name='Foto de Perfil (Archivo)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80', verbose_name='Foto / Avatar (URL alternativa)'),
        ),
    ]
