# Generated by Django 5.2.17 on 2026-08-26 15:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('status', models.CharField(choices=[('PERMITIDO', 'Acceso Permitido (Al día)'), ('VENCIDO', 'Acceso Denegado (Membresía Vencida)'), ('PENDIENTE', 'Acceso Denegado (Pago Pendiente)'), ('INACTIVO', 'Acceso Denegado (Socio Inactivo)')], default='PERMITIDO', max_length=20, verbose_name='Estado de Acceso')),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Acceso')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observaciones / Mensaje')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='members.member', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Registro de Acceso / Check-in',
                'verbose_name_plural': 'Registros de Acceso / Check-ins',
                'ordering': ['-checkin_time'],
            },
        ),
    ]
